server:
  port: 10080
  max-http-header-size: 102400 # 增加请求头的长度

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

jackson:
  serialization:
    FAIL_ON_EMPTY_BEANS: false


data_api:
  source_url: 10.101.16.170:8020
  target_url: 10.104.3.41:8020

domain:
  request:
    vendor:
      - media.st.dl.pinyuncloud.com
      - ltsbsy.qq.com
